export function json2go(json: string, tagName = 'json', flatten = true): { go: string; error?: string } {
  let go = ''
  const seen: Record<string, string[]> = {}
  const stack: string[] = []
  let accumulator = ''
  let parent = ''

  let data: any
  try {
    data = JSON.parse(json.replace(/\.0/g, '.1'))
  } catch (e: any) {
    return { go: '', error: e.message }
  }

  const typename = format('AutoGenerated')
  go += `type ${typename} `
  parseScope(data)

  return { go: flatten ? go + accumulator : go }

  function parseScope(scope: any, depth = 0) {
    if (typeof scope === 'object' && scope !== null) {
      if (Array.isArray(scope)) {
        let sliceType: string | undefined
        for (let i = 0; i < scope.length; i++) {
          const t = goType(scope[i])
          if (!sliceType) sliceType = t
          else if (sliceType !== t) {
            sliceType = 'interface{}'
            break
          }
        }
        const slice = flatten && sliceType && ['struct', 'slice'].includes(sliceType) ? `[]${parent}` : '[]'
        if (flatten && depth >= 2) appender(slice)
        else go += slice

        if (sliceType === 'struct') {
          const allFields: Record<string, { value: any; count: number }> = {}
          for (let i = 0; i < scope.length; i++) {
            const keys = Object.keys(scope[i])
            for (const k of keys) {
              if (!allFields[k]) {
                allFields[k] = { value: scope[i][k], count: 0 }
              }
              allFields[k].count++
            }
          }
          const struct: Record<string, any> = {}
          const omitempty: Record<string, boolean> = {}
          for (const keyname of Object.keys(allFields)) {
            struct[keyname] = allFields[keyname].value
            omitempty[keyname] = allFields[keyname].count !== scope.length
          }
          parseStruct(depth + 1, struct, tagName, omitempty)
        } else if (sliceType === 'slice') {
          parseScope(scope[0], depth)
        } else {
          if (flatten && depth >= 2) appender(sliceType || 'interface{}')
          else go += sliceType || 'interface{}'
        }
      } else {
        if (flatten && depth >= 2) appender(parent)
        parseStruct(depth + 1, scope, tagName)
      }
    } else {
      if (flatten && depth >= 2) appender(goType(scope))
      else go += goType(scope)
    }
  }

  function parseStruct(depth: number, scope: Record<string, any>, tagName = 'json', omitempty?: Record<string, boolean>) {
    if (flatten) stack.push(depth >= 2 ? '\n' : '')

    if (flatten && depth >= 2) {
      const parentType = `type ${parent}`
      const scopeKeys = Object.keys(scope).map(format)
      if (parent in seen && JSON.stringify(scopeKeys) === JSON.stringify(seen[parent])) {
        stack.pop()
        return
      }
      seen[parent] = scopeKeys
      appender(`${parentType} struct {\n`)
      let innerTabs = 0
      for (const [i, keyname] of Object.keys(scope).entries()) {
        appender('\t')
        const tn = format(keyname)
        appender(tn + ' ')
        parent = tn
        parseScope(scope[keyname], depth)
        appender(' `' + tagName + ':"' + keyname)
        if (omitempty && omitempty[keyname]) appender(',omitempty')
        appender('`\n')
      }
      appender('}\n')
    } else {
      go += 'struct {\n'
      for (const keyname of Object.keys(scope)) {
        go += '\t'
        const tn = format(keyname)
        go += tn + ' '
        parent = tn
        parseScope(scope[keyname], depth)
        go += ' `' + tagName + ':"' + keyname
        if (omitempty && omitempty[keyname]) go += ',omitempty'
        go += '`\n'
      }
      go += '}'
    }

    if (flatten) {
      if (depth === 1) go += '\n'
      accumulator += stack.pop()
    }
  }

  function append(str: string) { go += str }
  function appender(str: string) { stack[stack.length - 1] += str }
}

function format(str: string): string {
  if (!str) return ''
  if (/^\d+$/.test(str)) str = 'Num' + str
  else if (/^\d/.test(str)) {
    const numbers: Record<string, string> = { '0': 'Zero_', '1': 'One_', '2': 'Two_', '3': 'Three_', '4': 'Four_', '5': 'Five_', '6': 'Six_', '7': 'Seven_', '8': 'Eight_', '9': 'Nine_' }
    str = numbers[str[0]] + str.slice(1)
  }
  return toProperCase(str).replace(/[^a-z0-9]/gi, '') || 'NAMING_FAILED'
}

function goType(val: any): string {
  if (val === null) return 'interface{}'
  switch (typeof val) {
    case 'string':
      if (/\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?(\+\d\d:\d\d|Z)/.test(val)) return 'time.Time'
      return 'string'
    case 'number':
      if (val % 1 === 0) {
        if (val > -2147483648 && val < 2147483647) return 'int'
        return 'int64'
      }
      return 'float64'
    case 'boolean': return 'bool'
    case 'object':
      if (Array.isArray(val)) return 'slice'
      return 'struct'
    default: return 'interface{}'
  }
}

function toProperCase(str: string): string {
  const commonInitialisms = ['ACL', 'API', 'ASCII', 'CPU', 'CSS', 'DNS', 'EOF', 'GUID', 'HTML', 'HTTP', 'HTTPS', 'ID', 'IP', 'JSON', 'LHS', 'QPS', 'RAM', 'RHS', 'RPC', 'SLA', 'SMTP', 'SQL', 'SSH', 'TCP', 'TLS', 'TTL', 'UDP', 'UI', 'UID', 'UUID', 'URI', 'URL', 'UTF8', 'VM', 'XML', 'XMPP', 'XSRF', 'XSS']
  return str
    .replace(/(^|[^a-zA-Z])([a-z]+)/g, (_, sep, frag) =>
      commonInitialisms.includes(frag.toUpperCase()) ? sep + frag.toUpperCase() : sep + frag[0].toUpperCase() + frag.slice(1).toLowerCase()
    )
    .replace(/([A-Z])([a-z]+)/g, (_, sep, frag) =>
      commonInitialisms.includes(sep + frag.toUpperCase()) ? (sep + frag).toUpperCase() : sep + frag
    )
}
