import yaml from 'js-yaml'

function format(str: string): string {
  if (!str) return ''
  if (/^\d+$/.test(str)) str = 'Num' + str
  else if (/^\d/.test(str)) {
    const n: Record<string, string> = { '0': 'Zero_', '1': 'One_', '2': 'Two_', '3': 'Three_', '4': 'Four_', '5': 'Five_', '6': 'Six_', '7': 'Seven_', '8': 'Eight_', '9': 'Nine_' }
    str = n[str[0]] + str.slice(1)
  }
  return toProperCase(str).replace(/[^a-z0-9]/gi, '') || 'NAMING_FAILED'
}

function toProperCase(s: string): string {
  const ci = ['API', 'CPU', 'CSS', 'DNS', 'EOF', 'GUID', 'HTML', 'HTTP', 'HTTPS', 'ID', 'IP', 'JSON', 'RAM', 'SQL', 'SSH', 'TCP', 'TLS', 'TTL', 'UI', 'UID', 'UUID', 'URI', 'URL', 'UTF8', 'VM', 'XML', 'YAML']
  return s.replace(/(^|[^a-zA-Z])([a-z]+)/g, (_, sep, frag) =>
    ci.includes(frag.toUpperCase()) ? sep + frag.toUpperCase() : sep + frag[0].toUpperCase() + frag.slice(1).toLowerCase()
  ).replace(/([A-Z])([a-z]+)/g, (_, sep, frag) =>
    ci.includes(sep + frag.toUpperCase()) ? (sep + frag).toUpperCase() : sep + frag
  )
}

function goType(val: any, depth = 0): string {
  if (val === null) return 'interface{}'
  switch (typeof val) {
    case 'string': return 'string'
    case 'number': return val % 1 === 0 ? 'int' : 'float64'
    case 'boolean': return 'bool'
    case 'object':
      if (Array.isArray(val)) {
        if (val.length === 0) return '[]interface{}'
        const inner = goType(val[0], depth + 1)
        if (inner.startsWith('struct') || inner.startsWith('[]struct')) return `[]${inner}`
        return `[]${inner}`
      }
      return goStruct(val, depth + 1)
    default: return 'interface{}'
  }
}

function goStruct(obj: Record<string, any>, depth = 0): string {
  let s = 'struct {\n'
  for (const [key, val] of Object.entries(obj)) {
    s += '\t'.repeat(depth + 1)
    s += `${format(key)} ${goType(val, depth)} \`yaml:"${key}"\`\n`
  }
  s += '\t'.repeat(depth) + '}'
  return s
}

export function yaml2go(yamlStr: string): { go?: string; error?: string } {
  try {
    const doc = yaml.load(yamlStr)
    if (doc === null || doc === undefined) return { error: 'YAML 内容为空' }
    const typeName = 'AutoGenerated'
    const result = `type ${typeName} ${goType(doc, 0)}`
    return { go: result }
  } catch (e: any) {
    return { error: e.message || 'YAML 解析失败' }
  }
}
